### PR TITLE
Configurable git client timeout

### LINKED ISSUE #2188: [SURE-7783] Fleet 0.9.0 having trouble with bitbucket syncing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Gitjob in cattle-fleet-system namespace is giving following error for all the gitjobs after Rancher upgrade to 2.8.2

time="2024-02-28T11:00:35Z" level=error msg="Error fetching latest commit: Get \"https://xxx/xposer.git/info/refs?service=git-upload-pack\": context deadline exceeded"

If I do force resync it becomes active but after sometime it again goes to failed state with the above error

### Expected Behavior

repo should sync without any error

### Steps To Reproduce

_No response_

### Environment

```markdown
- Architecture:
- Fleet Version: 0.9.0
- Cluster:
  - Provider: EKS
  - Options:
  - Kubernetes Version: 1.26
```

### Logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by p-se**
Fixes #2188

Also fixes an issue in the config reconciler which has prevented the
config from being reloaded when it was changed.

### CODE REVIEW

File: integrationtests/cli/cleanup/suite_test.go [hunk 1]
```diff
@@ -49,7 +49,7 @@ func (g *getter) GetNamespace() string {
 
 func TestFleetCLICleanUp(t *testing.T) {
 	RegisterFailHandler(Fail)
-	RunSpecs(t, "Fleet CLI Cleanup Suite")
+	RunSpecs(t, "GitJob Controller Suite")
```
Comment (manno) [inline integrationtests/cli/cleanup/suite_test.go:52]: This seems wrong.
```suggestion
	RunSpecs(t, "Fleet CLI Cleanup")
```

File: integrationtests/gitjob/controller/controller_test.go [hunk 2]
```diff
@@ -43,6 +44,9 @@ var _ = Describe("GitJob controller", func() {
 		)
 
 		JustBeforeEach(func() {
+			config.Set(&config.Config{
```
Comment (manno) [inline integrationtests/gitjob/controller/controller_test.go:47]: This will affect all integration tests running after this one, I think? 
But that doesn't matter I guess, is this just for initialization? Instead of initializing the config in some tests, could we make the code work with an empty config instead?

File: integrationtests/cli/cleanup/suite_test.go (hunk 1 above)
Comment (p-se) [reply integrationtests/cli/cleanup/suite_test.go]: It was the other suite that needed correction.

File: integrationtests/gitjob/controller/controller_test.go (hunk 2 above)
Comment (p-se) [reply integrationtests/gitjob/controller/controller_test.go]: I've added the initialization to the suite instead of the tests where possible and initialized it empty where possible.

**Review by 0xavi0 — APPROVED** [review]
looks good to me
